services:
  - type: web
    name: stefan-api-test-3
    env: python
    plan: starter
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ELEVENLABS_API_KEY
        sync: false
        description: "ElevenLabs API-nyckel för TTS-funktionalitet"
